
---

```dockerfile
FROM python:3.10-slim

# Установка рабочей директории
WORKDIR /app

# Подтягиваем зависимости
COPY requirements.txt .

# Установим зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копирование кода
COPY ./app ./app

# Запуск uvicorn сервера
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

